$(document).ready(function(){
		$("#list_course1").click(function(){
			$("#stat").toggle();;
			$("#individual_courses1").hide();
			$("#individual_courses2").hide();
			$("#individual_courses3").hide();
			$("#individual_courses4").hide();
			$("#individual_courses5").hide();
			$("#individual_courses6").hide();
			$("#individual_courses7").hide();
			$("#individual_courses8").hide();
			$("#individual_courses9").hide();
			$("#individual_courses10").hide();
			$("#individual_courses11").hide();
			$("#individual_courses12").hide();
			$("#individual_courses13").hide();
			$("#individual_courses14").hide();
			$("#individual_courses15").hide();
			$("#individual_courses16").hide();
			$("#individual_courses17").hide();
			$("#individual_courses18").hide();
			$("#individual_courses19").hide();
			$("#individual_courses20").hide();

		});
});
$(document).ready(function(){
		$("#1").click(function(){
			$("#stat").hide();
			$("#individual_courses1").show();
			$("#individual_courses2").hide();
			$("#individual_courses3").hide();
			$("#individual_courses4").hide();
			$("#individual_courses5").hide();
			$("#individual_courses6").hide();
			$("#individual_courses7").hide();
			$("#individual_courses8").hide();
			$("#individual_courses9").hide();
			$("#individual_courses10").hide();
			$("#individual_courses11").hide();
			$("#individual_courses12").hide();
			$("#individual_courses13").hide();
			$("#individual_courses14").hide();
			$("#individual_courses15").hide();
			$("#individual_courses16").hide();
			$("#individual_courses17").hide();
			$("#individual_courses18").hide();
			$("#individual_courses19").hide();
			$("#individual_courses20").hide();
		});

});

$(document).ready(function(){
		$("#2").click(function(){
			$("#stat").hide();
			$("#individual_courses1").hide();
			$("#individual_courses2").show();
			$("#individual_courses3").hide();
			$("#individual_courses4").hide();
			$("#individual_courses5").hide();
			$("#individual_courses6").hide();
			$("#individual_courses7").hide();
			$("#individual_courses8").hide();
			$("#individual_courses9").hide();
			$("#individual_courses10").hide();
			$("#individual_courses11").hide();
			$("#individual_courses12").hide();
			$("#individual_courses13").hide();
			$("#individual_courses14").hide();
			$("#individual_courses15").hide();
			$("#individual_courses16").hide();
			$("#individual_courses17").hide();
			$("#individual_courses18").hide();
			$("#individual_courses19").hide();
			$("#individual_courses20").hide();
		});

});

$(document).ready(function(){
		$("#3").click(function(){
			$("#stat").hide();
			$("#individual_courses1").hide();
			$("#individual_courses2").hide();
			$("#individual_courses3").show();
			$("#individual_courses4").hide();
			$("#individual_courses5").hide();
			$("#individual_courses6").hide();
			$("#individual_courses7").hide();
			$("#individual_courses8").hide();
			$("#individual_courses9").hide();
			$("#individual_courses10").hide();
			$("#individual_courses11").hide();
			$("#individual_courses12").hide();
			$("#individual_courses13").hide();
			$("#individual_courses14").hide();
			$("#individual_courses15").hide();
			$("#individual_courses16").hide();
			$("#individual_courses17").hide();
			$("#individual_courses18").hide();
			$("#individual_courses19").hide();
			$("#individual_courses20").hide();
		});

});

$(document).ready(function(){
		$("#4").click(function(){
			$("#stat").hide();
			$("#individual_courses1").hide();
			$("#individual_courses2").hide();
			$("#individual_courses3").hide();
			$("#individual_courses4").show();
			$("#individual_courses5").hide();
			$("#individual_courses6").hide();
			$("#individual_courses7").hide();
			$("#individual_courses8").hide();
			$("#individual_courses9").hide();
			$("#individual_courses10").hide();
			$("#individual_courses11").hide();
			$("#individual_courses12").hide();
			$("#individual_courses13").hide();
			$("#individual_courses14").hide();
			$("#individual_courses15").hide();
			$("#individual_courses16").hide();
			$("#individual_courses17").hide();
			$("#individual_courses18").hide();
			$("#individual_courses19").hide();
			$("#individual_courses20").hide();
		});

});

$(document).ready(function(){
		$("#5").click(function(){
			$("#stat").hide();
			$("#individual_courses1").hide();
			$("#individual_courses2").hide();
			$("#individual_courses3").hide();
			$("#individual_courses4").hide();
			$("#individual_courses5").show();
			$("#individual_courses6").hide();
			$("#individual_courses7").hide();
			$("#individual_courses8").hide();
			$("#individual_courses9").hide();
			$("#individual_courses10").hide();
			$("#individual_courses11").hide();
			$("#individual_courses12").hide();
			$("#individual_courses13").hide();
			$("#individual_courses14").hide();
			$("#individual_courses15").hide();
			$("#individual_courses16").hide();
			$("#individual_courses17").hide();
			$("#individual_courses18").hide();
			$("#individual_courses19").hide();
			$("#individual_courses20").hide();
		});

});
$(document).ready(function(){
		$("#6").click(function(){
			$("#stat").hide();
			$("#individual_courses1").hide();
			$("#individual_courses2").hide();
			$("#individual_courses3").hide();
			$("#individual_courses4").hide();
			$("#individual_courses5").hide();
			$("#individual_courses6").show();
			$("#individual_courses7").hide();
			$("#individual_courses8").hide();
			$("#individual_courses9").hide();
			$("#individual_courses10").hide();
			$("#individual_courses11").hide();
			$("#individual_courses12").hide();
			$("#individual_courses13").hide();
			$("#individual_courses14").hide();
			$("#individual_courses15").hide();
			$("#individual_courses16").hide();


		$("#individual_courses17").hide();
			$("#individual_courses18").hide();
			$("#individual_courses19").hide();
			$("#individual_courses20").hide();
		});
});

$(document).ready(function(){
		$("#7").click(function(){
			$("#stat").hide();
			$("#individual_courses1").hide();
			$("#individual_courses2").hide();
			$("#individual_courses3").hide();
			$("#individual_courses4").hide();
			$("#individual_courses5").hide();
			$("#individual_courses6").hide();
			$("#individual_courses7").show();
			$("#individual_courses8").hide();
			$("#individual_courses9").hide();
			$("#individual_courses10").hide();
			$("#individual_courses11").hide();
			$("#individual_courses12").hide();
			$("#individual_courses13").hide();
			$("#individual_courses14").hide();
			$("#individual_courses15").hide();
			$("#individual_courses16").hide();
			$("#individual_courses17").hide();
			$("#individual_courses18").hide();
			$("#individual_courses19").hide();
			$("#individual_courses20").hide();
		});
});

(document).ready(function(){
		$("#8").click(function(){
			$("#stat").hide();
			$("#individual_courses1").hide();
			$("#individual_courses2").hide();
			$("#individual_courses3").hide();
			$("#individual_courses4").hide();
			$("#individual_courses5").hide();
			$("#individual_courses6").hide();
			$("#individual_courses7").hide();
			$("#individual_courses8").show();
			$("#individual_courses9").hide();
			$("#individual_courses10").hide();
			$("#individual_courses11").hide();
			$("#individual_courses12").hide();
			$("#individual_courses13").hide();
			$("#individual_courses14").hide();
			$("#individual_courses15").hide();
			$("#individual_courses16").hide();
			$("#individual_courses17").hide();
			$("#individual_courses18").hide();
			$("#individual_courses19").hide();
			$("#individual_courses20").hide();
});

		});
$(document).ready(function(){
		$("#9").click(function(){
			$("#stat").hide();
			$("#individual_courses1").hide();
			$("#individual_courses2").hide();
			$("#individual_courses3").hide();
			$("#individual_courses4").hide();
			$("#individual_courses5").hide();
			$("#individual_courses6").hide();
			$("#individual_courses7").hide();
			$("#individual_courses8").hide();
			$("#individual_courses9").show();
			$("#individual_courses10").hide();
			$("#individual_courses11").hide();
			$("#individual_courses12").hide();
			$("#individual_courses13").hide();
			$("#individual_courses14").hide();
			$("#individual_courses15").hide();
			$("#individual_courses16").hide();
			$("#individual_courses17").hide();
			$("#individual_courses18").hide();
			$("#individual_courses19").hide();
			$("#individual_courses20").hide();
		});
});


$(document).ready(function(){
		$("#10").click(function(){
			$("#stat").hide();
			$("#individual_courses1").hide();
			$("#individual_courses2").hide();
			$("#individual_courses3").hide();
			$("#individual_courses4").hide();
			$("#individual_courses5").hide();
			$("#individual_courses6").hide();
			$("#individual_courses7").hide();
			$("#individual_courses8").hide();
			$("#individual_courses9").hide();
			$("#individual_courses10").show();
			$("#individual_courses11").hide();
			$("#individual_courses12").hide();
			$("#individual_courses13").hide();
			$("#individual_courses14").hide();
			$("#individual_courses15").hide();
			$("#individual_courses16").hide();
			$("#individual_courses17").hide();
			$("#individual_courses18").hide();
			$("#individual_courses19").hide();
			$("#individual_courses20").hide();
		});
});

$(document).ready(function(){
		$("#11").click(function(){
			$("#stat").hide();
			$("#individual_courses1").hide();
			$("#individual_courses2").hide();
			$("#individual_courses3").hide();
			$("#individual_courses4").hide();
			$("#individual_courses5").hide();
			$("#individual_courses6").hide();
			$("#individual_courses7").hide();
			$("#individual_courses8").hide();
			$("#individual_courses9").hide();
			$("#individual_courses10").hide();
			$("#individual_courses11").show();
			$("#individual_courses12").hide();
			$("#individual_courses13").hide();
			$("#individual_courses14").hide();
			$("#individual_courses15").hide();
			$("#individual_courses16").hide();
			$("#individual_courses17").hide();
			$("#individual_courses18").hide();
			$("#individual_courses19").hide();
			$("#individual_courses20").hide();
		});
});


$(document).ready(function(){
		$("#12").click(function(){
			$("#stat").hide();
			$("#individual_courses1").hide();
			$("#individual_courses2").hide();
			$("#individual_courses3").hide();
			$("#individual_courses4").hide();
			$("#individual_courses5").hide();
			$("#individual_courses6").hide();
			$("#individual_courses7").hide();
			$("#individual_courses8").hide();
			$("#individual_courses9").hide();
			$("#individual_courses10").hide();
			$("#individual_courses11").hide();
			$("#individual_courses12").show();
			$("#individual_courses13").hide();
			$("#individual_courses14").hide();
			$("#individual_courses15").hide();
			$("#individual_courses16").hide();
			$("#individual_courses17").hide();
			$("#individual_courses18").hide();
			$("#individual_courses19").hide();
			$("#individual_courses20").hide();
		});
});


$(document).ready(function(){
		$("#13").click(function(){
			$("#stat").hide();
			$("#individual_courses1").hide();
			$("#individual_courses2").hide();
			$("#individual_courses3").hide();
			$("#individual_courses4").hide();
			$("#individual_courses5").hide();
			$("#individual_courses6").hide();
			$("#individual_courses7").hide();
			$("#individual_courses8").hide();
			$("#individual_courses9").hide();
			$("#individual_courses10").hide();
			$("#individual_courses11").hide();
			$("#individual_courses12").hide();
			$("#individual_courses13").show();
			$("#individual_courses14").hide();
			$("#individual_courses15").hide();
			$("#individual_courses16").hide();
			$("#individual_courses17").hide();
			$("#individual_courses18").hide();
			$("#individual_courses19").hide();
			$("#individual_courses20").hide();
		});
});


$(document).ready(function(){
		$("#14").click(function(){
			$("#stat").hide();
			$("#individual_courses1").hide();
			$("#individual_courses2").hide();
			$("#individual_courses3").hide();
			$("#individual_courses4").hide();
			$("#individual_courses5").hide();
			$("#individual_courses6").hide();
			$("#individual_courses7").hide();
			$("#individual_courses8").hide();
			$("#individual_courses9").hide();
			$("#individual_courses10").hide();
			$("#individual_courses11").hide();
			$("#individual_courses12").hide();
			$("#individual_courses13").hide();
			$("#individual_courses14").show();
			$("#individual_courses15").hide();
			$("#individual_courses16").hide();
			$("#individual_courses17").hide();
			$("#individual_courses18").hide();
			$("#individual_courses19").hide();
			$("#individual_courses20").hide();
		});
});

$(document).ready(function(){
		$("#15").click(function(){
			$("#stat").hide();
			$("#individual_courses1").hide();
			$("#individual_courses2").hide();
			$("#individual_courses3").hide();
			$("#individual_courses4").hide();
			$("#individual_courses5").hide();
			$("#individual_courses6").hide();
			$("#individual_courses7").hide();
			$("#individual_courses8").hide();
			$("#individual_courses9").hide();
			$("#individual_courses10").hide();
			$("#individual_courses11").hide();
			$("#individual_courses12").hide();
			$("#individual_courses13").hide();
			$("#individual_courses14").hide();
			$("#individual_courses15").show();
			$("#individual_courses16").hide();
			$("#individual_courses17").hide();
			$("#individual_courses18").hide();
			$("#individual_courses19").hide();
			$("#individual_courses20").hide();
		});
});


$(document).ready(function(){
		$("#16").click(function(){
			$("#stat").hide();
			$("#individual_courses1").hide();
			$("#individual_courses2").hide();
			$("#individual_courses3").hide();
			$("#individual_courses4").hide();
			$("#individual_courses5").hide();
			$("#individual_courses6").hide();
			$("#individual_courses7").hide();
			$("#individual_courses8").hide();
			$("#individual_courses9").hide();
			$("#individual_courses10").hide();
			$("#individual_courses11").hide();
			$("#individual_courses12").hide();
			$("#individual_courses13").hide();
			$("#individual_courses14").hide();
			$("#individual_courses15").hide();
			$("#individual_courses16").show();
			$("#individual_courses17").hide();
			$("#individual_courses18").hide();
			$("#individual_courses19").hide();
			$("#individual_courses20").hide();
		});
});


$(document).ready(function(){
		$("#17").click(function(){
			$("#stat").hide();
			$("#individual_courses1").hide();
			$("#individual_courses2").hide();
			$("#individual_courses3").hide();
			$("#individual_courses4").hide();
			$("#individual_courses5").hide();
			$("#individual_courses6").hide();
			$("#individual_courses7").hide();
			$("#individual_courses8").hide();
			$("#individual_courses9").hide();
			$("#individual_courses10").hide();
			$("#individual_courses11").hide();
			$("#individual_courses12").hide();
			$("#individual_courses13").hide();
			$("#individual_courses14").hide();
			$("#individual_courses15").hide();
			$("#individual_courses16").hide();
			$("#individual_courses17").show();
			$("#individual_courses18").hide();
			$("#individual_courses19").hide();
			$("#individual_courses20").hide();
		});
});


$(document).ready(function(){
		$("#18").click(function(){
			$("#stat").hide();
			$("#individual_courses1").hide();
			$("#individual_courses2").hide();
			$("#individual_courses3").hide();
			$("#individual_courses4").hide();
			$("#individual_courses5").hide();
			$("#individual_courses6").hide();
			$("#individual_courses7").hide();
			$("#individual_courses8").hide();
			$("#individual_courses9").hide();
			$("#individual_courses10").hide();
			$("#individual_courses11").hide();
			$("#individual_courses12").hide();
			$("#individual_courses13").hide();
			$("#individual_courses14").hide();
			$("#individual_courses15").hide();
			$("#individual_courses16").hide();
			$("#individual_courses17").hide();
			$("#individual_courses18").show();
			$("#individual_courses19").hide();
			$("#individual_courses20").hide();
		});
});


$(document).ready(function(){
		$("#19").click(function(){
			$("#stat").hide();
			$("#individual_courses1").hide();
			$("#individual_courses2").hide();
			$("#individual_courses3").hide();
			$("#individual_courses4").hide();
			$("#individual_courses5").hide();
			$("#individual_courses6").hide();
			$("#individual_courses7").hide();
			$("#individual_courses8").hide();
			$("#individual_courses9").hide();
			$("#individual_courses10").hide();
			$("#individual_courses11").hide();
			$("#individual_courses12").hide();
			$("#individual_courses13").hide();
			$("#individual_courses14").hide();
			$("#individual_courses15").hide();
			$("#individual_courses16").hide();
			$("#individual_courses17").hide();
			$("#individual_courses18").hide();
			$("#individual_courses19").show();
			$("#individual_courses20").hide();
		});
});


$(document).ready(function(){
		$("#20").click(function(){
			$("#stat").hide();
			$("#individual_courses1").hide();
			$("#individual_courses2").hide();
			$("#individual_courses3").hide();
			$("#individual_courses4").hide();
			$("#individual_courses5").hide();
			$("#individual_courses6").hide();
			$("#individual_courses7").hide();
			$("#individual_courses8").hide();
			$("#individual_courses9").hide();
			$("#individual_courses10").hide();
			$("#individual_courses11").hide();
			$("#individual_courses12").hide();
			$("#individual_courses13").hide();
			$("#individual_courses14").hide();
			$("#individual_courses15").hide();
			$("#individual_courses16").hide();
			$("#individual_courses17").hide();
			$("#individual_courses18").hide();
			$("#individual_courses19").hide();
			$("#individual_courses20").show();
});

		});
